config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("mytop5.urls")),
    path('accounts/', include('allauth.urls')),
]

mytop5/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.top, name="top"),
    path("home/", views.home, name="home"),
    path("create/", views.create, name="create"),
    path('detail/<int:pk>/', views.detail, name="detail"),
    path('edit/<int:pk>/', views.edit, name="edit"),
    path('settings/<int:pk>/', views.settingsView, name="settings"),
    path("img/<str:imgType>/<int:pk>/", views.imgView),
]

mytop5/models.py
from django.db import models
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.core import validators
from django.conf import settings
import datetime


class MyUserManager(BaseUserManager):
    def create_user(self, email, display_name, sns_type, password=None):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            display_name=display_name,
            sns_type=sns_type,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, display_name, sns_type, password=None):
        """
        Creates and saves a User with the given email and password.
        """

        user = self.create_user(
            email,
            password=password,
            display_name=display_name,
            sns_type=sns_type
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class CustomUser(AbstractBaseUser):
    class Meta:
        verbose_name_plural = 'ユーザー情報'
    SNS_TYPE = [
        ("T", "https://twitter.com/"),
        ("I", "https://www.instagram.com/"),
        ("N", "なし"),
    ]
    email = models.EmailField(
        verbose_name='メールアドレス',
        max_length=255,
        unique=True,
    )
    display_name = models.CharField(max_length=30, verbose_name="SNSのユーザー名")
    sns_type = models.CharField(
        max_length=4, choices=SNS_TYPE, verbose_name="SNSの種類", default="N")
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['display_name', 'sns_type']

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        return self.is_admin


class Ranking(models.Model):
    class Meta:
        verbose_name_plural = "ランキングの集合"
    title = models.CharField(max_length=18, verbose_name="ランキング名")
    description = models.TextField(verbose_name="ランキングの説明", blank=True)
    created_date = models.DateTimeField(
        default=datetime.datetime.now, verbose_name="作成日時")
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)  # ユーザーの外部参照キー


class Detail(models.Model):
    class Meta:
        verbose_name_plural = "ランキング詳細情報"
    title = models.CharField(max_length=20, verbose_name="名前")
    rank = models.IntegerField(validators=[validators.MinValueValidator(1),
                                           validators.MaxValueValidator(5)], verbose_name="ランク")
    description = models.TextField(verbose_name="ランキングの説明", blank=True)
    ranking = models.ForeignKey(Ranking,
                                on_delete=models.CASCADE)  # ランキングの外部参照キー

mytop5/forms.py
import re
from django import forms


class RankingForm(forms.Form):
    title = forms.CharField(max_length=18, label="ランキング名")
    description = forms.CharField(
        max_length=300, widget=forms.Textarea, label="ランキングの説明", required=False)


class DetailForm(forms.Form):
    dtitle1 = forms.CharField(max_length=20, label="名前")
    ddescription1 = forms.CharField(label="ランキングの説明", required=False)
    dtitle2 = forms.CharField(max_length=20, label="名前")
    ddescription2 = forms.CharField(label="ランキングの説明", required=False)
    dtitle3 = forms.CharField(max_length=20, label="名前")
    ddescription3 = forms.CharField(label="ランキングの説明", required=False)
    dtitle4 = forms.CharField(max_length=20, label="名前")
    ddescription4 = forms.CharField(label="ランキングの説明", required=False)
    dtitle5 = forms.CharField(max_length=20, label="名前")
    ddescription5 = forms.CharField(label="ランキングの説明", required=False)


class SettingsForm(forms.Form):
    NAME_REGEX = re.compile(r"^[a-zA-Z0-9._]{1,30}$")
    SNS_TYPE = (
        ("T", "Twitter"),
        ("I", "Instagram"),
        ("N", "なし"),
    )
    email = forms.EmailField(
        label="メールアドレス",
        max_length=255,
        widget=forms.TextInput(attrs={"placeholder": "mytop5@example.com"})
    )
    display_name = forms.RegexField(
        regex=NAME_REGEX, label="リンクするSNSプロフィールのユーザー名（@を除く）", widget=forms.TextInput(attrs={"placeholder": "example_name"}))
    sns_type = forms.ChoiceField(
        choices=SNS_TYPE, widget=forms.Select, label="リンクするSNSの種類")

mytop5/views.py
import base64
from django.http import HttpResponse, Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from . import image
from .models import Ranking, Detail
from .forms import RankingForm, DetailForm, SettingsForm


def top(request):
    # top画面
    return render(request, "mytop5/top.html")


@login_required
def home(request):
    # マイページ
    userData = get_object_or_404(get_user_model(), id=request.user.id)
    rankingInfo = Ranking.objects.filter(
        user=userData).order_by("-created_date")
    return render(request, "mytop5/home.html", {"rankingInfo": rankingInfo, "userData": userData})


@login_required
def create(request):
    userData = get_object_or_404(get_user_model(), id=request.user.id)
    if request.method == "POST":
        rform = RankingForm(request.POST)
        dform = DetailForm(request.POST)
        if rform.is_valid() and dform.is_valid():
            rankingData = Ranking.objects.create(
                title=rform.cleaned_data["title"],
                description=rform.cleaned_data["description"],
                user=userData,
            )

            rankObj = []
            for i in range(1, 6):
                rankObj.append(Detail(
                    title=dform.cleaned_data[f"dtitle{i}"],
                    description=dform.cleaned_data[f"ddescription{i}"],
                    rank=i,
                    ranking=rankingData)
                )
            Detail.objects.bulk_create(rankObj)
            rankObj.clear()

            return redirect("detail", rankingData.id)

    return render(request, "mytop5/create.html", {"userData": userData})


@login_required
def edit(request, pk):
    userData = get_object_or_404(get_user_model(), id=request.user.id)
    rankingData = get_object_or_404(Ranking, user=userData, id=pk)
    if pk != rankingData.id:
        # 本当にランキング情報が存在するかどうか
        raise Http404
    detailData = Detail.objects.filter(ranking=rankingData)
    if request.method == "POST":
        if "ranking_delete" in request.POST:
            rankingData.delete()
            return redirect("home")

        rform = RankingForm(request.POST)
        dform = DetailForm(request.POST)
        if rform.is_valid() and dform.is_valid():
            rankingData.title = rform.cleaned_data["title"]
            rankingData.description = rform.cleaned_data["description"]
            rankingData.user = userData
            rankingData.save()

            i = 1
            for item in detailData:
                item.title = dform.cleaned_data[f"dtitle{ i }"]
                item.description = dform.cleaned_data[f"ddescription{ i }"]
                item.ranking = rankingData
                item.save()
                i += 1
        return redirect("detail", rankingData.id)

    return render(request, "mytop5/edit.html", {"userData": userData, "rankingData": rankingData, "detailData": detailData})


def detail(request, pk):
    # ランキング詳細画面
    isReal = False
    rankingInfo = get_object_or_404(Ranking, id=pk)
    rankData = Detail.objects.filter(ranking=rankingInfo).order_by("rank")
    if rankingInfo.user == request.user:
        isReal = True
    return render(request, "mytop5/detail.html", {"rankingInfo": rankingInfo, "rankData": rankData, "isReal": isReal})


@login_required
def settingsView(request, pk):
    if pk != request.user.id:
        # 本当に本人が本人の情報を確認しようとしているか
        raise Http404
    userData = get_object_or_404(get_user_model(), id=request.user.id)
    if request.method == "POST":
        form = SettingsForm(request.POST)
        if form.is_valid():
            userData.email = form.cleaned_data["email"]
            userData.display_name = form.cleaned_data["display_name"]
            userData.sns_type = form.cleaned_data["sns_type"]
            userData.save()
        return redirect("settings", userData.id)

    form = SettingsForm(
        initial={
            "email": userData.email,
            "display_name": userData.display_name,
            "sns_type": userData.sns_type,
        }
    )
    return render(request, "mytop5/settings.html", {"userData": userData, "form": form})


def imgView(request, imgType, pk):
    ranksetData = get_object_or_404(Ranking, id=pk)
    displayName = ranksetData.user.display_name
    title = ranksetData.title
    rankData = Detail.objects.filter(ranking=pk).order_by("rank")
    if not rankData:
        raise Http404
    rankDataset = []
    for item in rankData:
        rankDataset.append(item)
    imgBase64 = image.imgGenerator(
        rankDataset, title, displayName, imgType)  # base64エンコードされた文字列を受け取り
    binary = base64.b64decode(imgBase64)
    return HttpResponse(binary, content_type="image/png")

mytop5/templates/mytop5/create.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>新規作成 - myTop5</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/milligram/1.4.1/milligram.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;500&display=swap" rel="stylesheet"> 
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
</head>

<body>
  <div class="container">
    <nav>
      <h1>myTop5</h1>
      <div class="account-menu">
        <details>
          <summary><i class="fas fa-user-circle"></i></summary>
          <div class ="details-menu">
            <div class="username">@{{ request.user.display_name }}</div>
            <div><a href="{% url 'home' %}">マイページ</a></div>
            <div><a href="{% url 'settings' request.user.id %}">設定</a></div>
            <div><a href="{% url 'account_logout' %}">ログアウト</a></div>
          </div>
        </details>
      </div>
    </nav>
    
    {% if userData %}
    <div class="card card-purple">
      <h2>ランキング新規作成</h2>
      <p class="description">
        説明にはURLを入れることができます。<br>
        リンクが正しく動くためには、URLの左右両端にスペースの入力が必要です。
      </p>
    </div>
    <p class="notice text-required">*必須事項</p>

    <form action="{% url 'create' %}" method="post">
      {% csrf_token %}
      <div class="card">
        <h3>ランキング情報</h3>
        <label for="title">ランキング名（18文字以内）<span class="text-required">*</span></label>
        <input id="title" type="text" name="title" required>
        <label for="description">説明</label>
        <textarea id="description" name="description"></textarea>
      </div>
      <div class="card">
        {% with ''|center:5 as range %}
        {% for _ in range %}
          <h3>{{ forloop.counter }}位</h3>
          <label for="dtitle{{ forloop.counter }}">名前（20文字以内）<span class="text-required">*</span></label>
          <input id="dtitle{{ forloop.counter }}" type="text" name="dtitle{{ forloop.counter }}" required>
          <label for="ddescription{{ forloop.counter }}">説明</label>
          <textarea id="ddescription{{ forloop.counter }}" name="ddescription{{ forloop.counter }}"></textarea>
        {% endfor %}
        {% endwith %}
      </div>

      <input type="submit" value="作成">
    </form>
    {% endif %}

  </div>
</body>

</html>

mytop5/templates/mytop5/detail.html
{% load static %}
{% load custom_urlize %}
<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{rankingInfo.title}} by @{{rankingInfo.user.display_name}} - myTop5</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/milligram/1.4.1/milligram.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;500&display=swap" rel="stylesheet"> 
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="og:title" content="{{rankingInfo.title}} by @{{rankingInfo.user.display_name}}">
  <meta name="og:description" content="myTop5 - 様々なランキングのトップ5を作って、共有できるサイト">
  <meta name="og:image" content="https://mytop5app.herokuapp.com/img/twitter/{{rankingInfo.id}}/">
  <meta property="og:type" content="website">
  <meta property="og:url" content="https://mytop5app.herokuapp.com/detail/{{rankingInfo.id}}/">
</head>

<body>
  <div class="container">
    <nav>
      <h1>myTop5</h1>
    {% if request.user.is_authenticated %}
      <div class="account-menu">
        <details>
          <summary><i class="fas fa-user-circle"></i></summary>
          <div class ="details-menu">
            <div class="username">@{{ request.user.display_name }}</div>
            <div><a href="{% url 'home' %}">マイページ</a></div>
            <div><a href="{% url 'settings' request.user.id %}">設定</a></div>
            <div><a href="{% url 'account_logout' %}">ログアウト</a></div>
          </div>
        </details>
      </div>
    {% endif %}
    </nav>
    
    {% if rankingInfo %}
    <div class="card card-purple">
      <h2>{{rankingInfo.title}}</h2>
      {% if rankingInfo.user.sns_type != "N" %}
      <p class="username">作成者：<a href="{{rankingInfo.user.get_sns_type_display}}{{rankingInfo.user.display_name}}/" target="_blank" rel="noopener noreferrer nofollow">@{{rankingInfo.user.display_name}}</a></p>
      {% else %}
      <p class="username">作成者：@{{rankingInfo.user.display_name}}</p>
      {% endif %}
      <p class="description">{{ rankingInfo.description|urlize|custom_urlize|linebreaksbr }}</p>
    </div>
    {% if rankData %}
    {% if request.user.is_authenticated and request.user.id == rankingInfo.user.id %}
    <a class="button button-edit" href="{% url 'edit' rankingInfo.id %}">編集する</a>
    {% endif %}
    <div class="card">
      {% for item in rankData %}
      <div class="card-rank">
        <div class="row">
          <div class="column column-25">
            <div class="rank-box rank-box-{{item.rank}}">
              {{item.rank}}位
            </div>
          </div>
          <div class="column column-75">
            <h3 class="card-rank-title">{{ item.title }}</h3>
            <p class="description">{{ item.description|urlize|custom_urlize|linebreaksbr }}</p>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    {% endif %}
    <div class="tweet-link">
      <a href="https://twitter.com/share?url=https://mytop5app.herokuapp.com/detail/{{rankingInfo.id}}/&text={{rankingInfo.title}} by @{{rankingInfo.user.display_name}} - myTop5&hashtags={{rankingInfo.title}}" rel="noopener noreferrer nofollow" target="_blank"><img src="{% static 'images/Twitter_Social_Icon_Circle_Color.png' %}"></a>
    </div>
    {% endif %}

  </div>
</body>

</html>

mytop5/templates/mytop5/edit.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>編集 - myTop5</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/milligram/1.4.1/milligram.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;500&display=swap" rel="stylesheet"> 
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
</head>

<body>
  <div class="container">
    <nav>
      <h1>myTop5</h1>
      <div class="account-menu">
        <details>
          <summary><i class="fas fa-user-circle"></i></summary>
          <div class ="details-menu">
            <div class="username">@{{ request.user.display_name }}</div>
            <div><a href="{% url 'home' %}">マイページ</a></div>
            <div><a href="{% url 'settings' request.user.id %}">設定</a></div>
            <div><a href="{% url 'account_logout' %}">ログアウト</a></div>
          </div>
        </details>
      </div>
    </nav>
    
    {% if userData %}
    <div class="card card-purple">
      <h2>ランキング編集</h2>
      <p class="description">
        説明にはURLを入れることができます。<br>
        リンクが正しく動くためには、URLの左右両端にスペースの入力が必要です。
      </p>
    </div>
    <p class="notice text-required">*必須事項</p>

    <form action="{% url 'edit' rankingData.id %}" method="post">
      {% csrf_token %}
      <div class="card">
        <h3>ランキング情報</h3>
        <label for="title">ランキング名（18文字以内）<span class="text-required">*</span></label>
        <input id="title" type="text" name="title" value="{{ rankingData.title }}" required>
        <label for="description">説明</label>
        <textarea id="description" name="description">{{ rankingData.description }}</textarea>
      </div>
      <div class="card">
        {% for item in detailData %}
          <h3>{{ forloop.counter }}位</h3>
          <label for="dtitle{{ forloop.counter }}">名前（20文字以内）<span class="text-required">*</span></label>
          <input id="dtitle{{ forloop.counter }}" type="text" name="dtitle{{ forloop.counter }}" value="{{ item.title }}" required>
          <label for="ddescription{{ forloop.counter }}">説明</label>
          <textarea id="ddescription{{ forloop.counter }}" name="ddescription{{ forloop.counter }}">{{ item.description }}</textarea>
        {% endfor %}
      </div>

      <div class="edit-buttons">
        <input type="submit" value="保存">
        <input class="delete-btn" name="ranking_delete" type="submit" value="削除">
      </div>

    </form>

    {% endif %}

  </div>
</body>

</html>

mytop5/templates/mytop5/home.html
{% load static %}
{% load custom_urlize %}
<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>マイページ - myTop5</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/milligram/1.4.1/milligram.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;500&display=swap" rel="stylesheet"> 
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
</head>

<body>
  <div class="container">
    <nav>
      <h1>myTop5</h1>
      <div class="account-menu">
        <details>
          <summary><i class="fas fa-user-circle"></i></summary>
          <div class ="details-menu">
            <div class="username">@{{ request.user.display_name }}</div>
            <div><a href="{% url 'home' %}">マイページ</a></div>
            <div><a href="{% url 'settings' request.user.id %}">設定</a></div>
            <div><a href="{% url 'account_logout' %}">ログアウト</a></div>
          </div>
        </details>
      </div>
    </nav>
    
    {% if userData %}
    <div class="card card-purple">
      <h2>@{{userData.display_name}}のマイページ</h2>
    </div>
    {% if rankingInfo %}
    {% for item in rankingInfo %}
    <div class="card card-home">
      <h3 class="card-rank-title">{{ item.title }}</h3>
      <p>{{ item.description|urlize|custom_urlize|linebreaksbr }}</p>
        <a class="button button-home" href="{% url 'detail' item.id %}">詳しく見る</a>
        <a class="button button-home" href="{% url 'edit' item.id %}">編集する</a>
      
    </div>
    {% endfor %}
    {% endif %}
    {% endif %}
    <div class="card card-plus">
      <a href="{% url 'create' %}"><i class="fas fa-plus-circle"></i>新規作成</a>
    </div>
  </div>
</body>

</html>

mytop5/templates/mytop5/settings.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>設定 - myTop5</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/milligram/1.4.1/milligram.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;500&display=swap" rel="stylesheet"> 
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
</head>

<body>
  <div class="container">
    <nav>
      <h1>myTop5</h1>
      <div class="account-menu">
        <details>
          <summary><i class="fas fa-user-circle"></i></summary>
          <div class ="details-menu">
            <div class="username">@{{ request.user.display_name }}</div>
            <div><a href="{% url 'home' %}">マイページ</a></div>
            <div><a href="{% url 'settings' request.user.id %}">設定</a></div>
            <div><a href="{% url 'account_logout' %}">ログアウト</a></div>
          </div>
        </details>
      </div>
    </nav>
    
    {% if userData %}
    <div class="card card-purple">
      <h2>@{{userData.display_name}}の設定</h2>
    </div>
    <div class="card">
        <form action="{% url 'settings' userData.id %}" method="post">
            {% csrf_token %}
            {{ form }}
            <dl>
                <dt>SNSプロフィールをリンクするとどうなるの？</dt>
                <dd>
                    設定したSNSのプロフィールページをランキング表示画面にリンクすることができます。
                </dd>
                <dt>現在リンクされているSNSプロフィールページ</dt>
                <dd>
                    {% if userData.sns_type != "N" %}
                    <a href="{{userData.get_sns_type_display}}{{userData.display_name}}/" target="_blank" rel="noopener noreferrer nofollow">{{userData.get_sns_type_display}}{{userData.display_name}}/</a>
                    {% else %}
                    未設定
                    {% endif %}
                </dd>
            </dl>
            
            <input type="submit" value="保存">
        </form>
    </div>
    {% endif %}

  </div>
</body>

</html>

mytop5/templates/mytop5/top.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>トップページ - myTop5</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/milligram/1.4.1/milligram.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;500&display=swap" rel="stylesheet"> 
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
</head>


<body>
    <div class="container">
        <nav>
            <h1>myTop5</h1>
        </nav>
           
        <p> 自分だけのトップ<ruby><rb>５</rb><rt>ファイブ</rt></ruby>を作ってみんなと共有しよう！</p>
        <br>
        <p>アカウントをお持ちの方</p><p class="line-height"><a href="{% url 'account_login' %}">ログイン＞＞</a></p>
        <p>アカウントをお持ちでない方</p><p><a href="{% url 'account_signup' %}">サインアップ＞＞</a></p>
    </div>
</body>

</html>